### ISSUE TITLE
[IMPROVE] Permitir que usuário da comunidade use o endpoint getUserByEmail

### ISSUE THREAD

**Issue by markinlimac** [fga-eps-mds/2021.1-Cartografia-social-api-gateway#55]
# Descrição:
Permitir que usuário da comunidade use o endpoint getUserByEmail

# Tarefas:
- [ ] Usuário mebro de comunidade deve ser possivel fazer chamadas para o endpoint getUserByEmail

# Critério de aceitação:
- [ ] Permitir que usuário da comunidade use o endpoint getUserByEmail

## Issue vinculada:
Não se aplica

**Comment by leossb36** [comment]
resolvido pelo membro da equipe na issue #58
